- hosts: controller
  tasks:
  - copy:
     src: hadoop-1.2.1-1.x86_64.rpm
     dest: /
  - copy:
     src: jdk-8u171-linux-x64.rpm
     dest: /
  - command: "rpm -i /hadoop-1.2.1-1.x86_64.rpm --force"
  - yum:
     name: /jdk-8u171-linux-x64.rpm
     disable_gpg_check: True
  - file:
     path: /nn
     state: directory
  - template:
     src: /hadooppb/hdfs-site.xml
     dest: /etc/hadoop/hdfs-site.xml
  - template:
     src: /hadooppb/core-site.xml
     dest: /etc/hadoop/core-site.xml
  - command: "hadoop namenode -format"
    
  - command: "hadoop-daemon.sh start namenode"
